language: python
sudo: required
python:
  # - 2.7
  - 3.2

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get update
  - sudo apt-get install -qq ibus python3-gi gir1.2-ibus-1.0 gir1.2-wnck-3.0
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
    ./test/setup_test.sh
    #pip3 install -r requirements.txt
    #pip3 install -r test/requirements.txt

script:
  # so to help eventual debug: knowing what exact versions are in use can be rather useful.
  # - pip freeze
  # Code static analysis
  # - pep8 --max-line-length=100 --exclude='*.pyc, *.cfg, *.log' --ignore='E402' alignak_app/*
  #- pylint --rcfile=.pylintrc alignak_webui/
  # No pep257 currently (Code doc compliance)
  # - pep257 --select=D300 alignak_webui
  # Code dynamic analysis
  # - cd test
  # - coverage erase
  - nosetests -xv --nologcapture --with-coverage --cover-package=alignak_app test/test_application.py
  # - coverage combine
  # - coverage report -m
  # - cd ..

# specific call to launch coverage data into coveralls.io
# after_success:
  # to get coverage data with relative paths and not absolute we have to
  # execute coveralls from the base directory of the project,
  # so we need to move the .coverage file here :
  # mv test/.coverage . && coveralls --rcfile=test/.coveragerc -v
  #mv test/.coverage . && coveralls -v
